server.port=${PORT:10000}
server.address=0.0.0.0

# ---- POSTGRESQL DATABASE CONFIGURATION ----
# Grab the host (dpg-...) and the database name from your Internal URL!
spring.datasource.url=postgresql://uni_versity_db_user:HdqsSpkEAsVUvpTGSinzoyPlm2f7ckuk@dpg-d83e8ofavr4c739nuqqg-a/uni_versity_db
spring.datasource.username=uni_versity_db_user
spring.datasource.password=HdqsSpkEAsVUvpTGSinzoyPlm2f7ckuk
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- HIBERNATE SETTINGS (THE MAGIC AUTOMATION) ----
# This tells Java to auto-build your tables inside the blank Postgres database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- JWT ----
app.jwt.secret=UNIVersityOJTSecretKey2026SuperSecureKeyForJWTTokenGeneration!@#$
app.jwt.expiration-ms=86400000

# ---- FILE UPLOAD ----
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
app.upload.dir=uploads/

# ---- SPRING SECURITY ----
spring.security.user.name=admin
spring.security.user.password=admin123

# ---- GMAIL SMTP (Forgot Password) ----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=systemg77777@gmail.com
spring.mail.password=gnnjlsahibeiixrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ---- THYMELEAF (disabled - using static HTML) ----
spring.thymeleaf.enabled=false

# ---- STATIC RESOURCES ----
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

#----- RESEND CODE ----
app.resend.api-key=re_Z2h3DfW4_32pGko1vPJZNr6Y3FHqu2ZjN
app.mail.from=onboarding@resend.dev

# ---- LOGGING ----
logging.level.com.university.ojt=INFO
logging.level.org.springframework.security=WARN

# ---- FRONTEND URL CONFIGURATION ----
app.frontend.url=https://university-backend-oijw.onrender.com
